dist: trusty
sudo: false

language: go
directories:
    - $HOME/.glide/cache
go:
  - 1.7

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - secure: PxV+ljvtJLjWP3ekkvBPoNhPeU4yGr1Ca3vjqUmmFRsVmbk3OnZ27HTQF00mYlkF9T1m8iHWGIlWF5LwxFWozjqnqoJTqOkBQvH4sUXTqkAVlDFz6YdzsMmwY83qONF8BYVRQKb0dTaT8gqmHjTbJOyF2VkFbweq4lwhFfC4muER4QBk3uWUCHN9/Ra/amWMBXfB64EXBhGQfgwrRhrJQ2kEGOwOul9Kk815sWGC50DSgrTnhKWwAqQoOqqxRImUFlYOHPiVDgU+s+i/qfExT7gFv/zGLUnzx+qI3zJonZwL4kmRDdebpuis3DrNIbrR4is68kCF5+Y4SY7fRZFgjgoEGKEWSd7dwImk4sGQ9iAC/63VaD4rq2Mlu7wmqhfFsmITk/kL5hPBNNmbvYxiYEgKkFQaO0O8IwMDTtHVc+nXOXEzFUt+Gm1uoKGkujV1G2QUcmMgN2WqbX3jEtx8HDPg6edrvYsB3gQ95dZBX95qOz81iQ7TTnt5I3zAAWVs5bYNk198pnGfvRwxMCPI9nBKMac2xNxGpRu2kqcLJxg47GZfmnEouGizthTDw/vhr9WvylFitreeo9js5v6+nNNIXE+6n3BtsC0wPPQJF5P1+Uk89VvzA9Br2ns5kRqa+YCzDXAjtfKG9z7JY1YXH+gNUVEIjKGEdux7Py9truA=
    - secure: aniIO/lIDp9cFiqj5Ph+/NqAqgD6cW5SamnF+AvruJEHPuFxR+AlyjItdWEeeq7LcB82CVu1buUxeqlTmiTgCh1t3gr5r3W5INKHm4SfuJ/TPIXd61G6R+mqdVCfypVhtMmeFCvO+KcF8nFcEaWVlBGmXYjj2FY9vsZKbSaBLkEq9S6tPjkZTL7wOTSQQw4mHZ84McgKWZ2KpXr19BNvZUTnTikjQo5mvdanrZ9ylQpnRW3ysA38JbBJGu9buSoArGC8Mb99oOIPmGbKK7/3X+vncKmfmgqvNGvnr7cqItpn6mScr2ot5ABmnO4C9pM6C5nGYq2vyTMnq4f4KBu0iz2/EA/RpwVcAmpuxJtBqYio3No2usLhqCBIX4i2ZhGTsthS2FmqOhYIoYvkVoFzW3wZLTZUXu2iSTXFX/IpxoJRTsgzmHhjfriFXzOu0NfXybxAVYUzZkwyfx7jw8/fxAnU7dC3HnZg0zXC7uq4p7UJmwORbWgx/XDF4J8ywI2oOvpUBYsMIl/qKqpj+yaUtDWvUL8rIBxreSrH7wRBPrXO5TpVtFste+hG0eqQUaxRhBepAUWmr5EZYYaCKJANQMDqNHO4kIGpfedZQOngRdS1Cm8gdpRyaliu87ZygU2lvDd0uNX071i/eqj4Olx/B7SKrk29nY7IyLlMa0Gn4Pc=

addons:
  apt:
    packages:
    - python
    - libsnappy-dev
    - zlib1g-dev
    - libbz2-dev
    - libgflags-dev

install:
  - go get -u github.com/Masterminds/glide
  - glide install

script:
  - pushd vendor/github.com/cockroachdb/c-rocksdb/internal
  - travis_wait 20 make shared_lib
  - strip librocksdb.so.5.0.2
  - popd

deploy:
  provider: releases
  api_key:
    secure: "W2Ztm+yJDfq64/NfFdCLC2+nLxxe5C6+Yic3gIHXv4qhygss4/3Ii/2gKt6I+lqcr1Wu/J8nCLmd1meVZ0SpZhPwEbWKEeZknqFxRZlxw53HzJJm2PtE1hLNeueQYSU25k455rt+iG1XgE1rIiaArSRKVB32trem/C80DwNDzUCqEKlq9g0UNGyl/+gK1ClhRtDyvLX4na/fMy6qbz7KtW3uYH5T8f6p0V6FUyo5XlR90F43Z+L+fM3hswh8o+KnuinZB+w7Cgrr9Zp0klj7sb1O9aNCgPX/vGdW2yCn5Gpg78P199vfXug6O3h1PghoKEbfWwRmzVcmMOGSmzVN3ubuEjfNMfGEoQThr30P4fxQNeJhFtCopE70zXcXg/Qg7fGdaSZwVA7/cVgYg4VmoB86ZiX5pqRvq65x9X7LKmSd/2jloLFRTAUAHZm+JcuKqNjtxNL77FT1M8e7eQGSqfqf6p34fEURykKR5snOuUPYd7VxwQwWbxvlpI3FdvAhylB+geviHoRahBfWKx2qEblCEEa2xga8tUrBoQtsQYPASmVOfTj8H4IcbaH+Axkqc3fSG+iiAD2bwNcsIMnQoceJFvbP7DtEBSGgLh12RiNkGuV4EPEEo8CPP3mXPz7bIjur2M7+PzSUUYsrMLMRsG6HpRhLeY7CW/0bHZHUVO0="
  file:
    - "./vendor/github.com/cockroachdb/c-rocksdb/internal/librocksdb.so.5.0.2"
  skip_cleanup: true
  on:
    branch: update_rocksdb
